### ISSUE TITLE
Image Sizing when using image array

### ISSUE THREAD

**Issue by saltatrix** [rprovost/ng-backstretch#11]
The images are sized correctly and they respond to the changes in viewport correctly when using a single image declared in the html.  However, when using the image array they appear fixed width and height at 100%.  As you change the viewport size the images are stretched and compressed instead of responding as they should and do with a single image.  Is there an attribute that can be passed?

**Comment by rprovost** [comment]
@saltatrix this issue should have be resolved with the latest release. https://github.com/rprovost/ng-backstretch/pull/13 looks to have resolved this.

**Comment by rprovost** [comment]
Since there has been no update on the status of this and it does appear to have been fixed, as indicated, I'm going to close this issue.
