### ISSUE TITLE
Backstretch on login page

### ISSUE THREAD

**Issue by jono99** [rprovost/ng-backstretch#22]
Hi there,

I'm using this module in our application which has a login page to enter. I only want to show backstretch on the login page, so between a couple of controllers and a service, it works to a point. Only problem is, it brakes when you refresh the page, throws the following error:
TypeError: d[0].offsetParent is null
...,height:"auto"},f=d[0].offsetWidth,g=f,h=d[0].offsetHeight>0?d[0].offsetHeight:d...
Points to h=d[0]

Any reason or background on this?

**Comment by rprovost** [comment]
@jono99 this should be fixed with the latest release.
