### ISSUE TITLE
Support dynamic src

### ISSUE THREAD

**Issue by jirihelmich** [rprovost/ng-backstretch#4]
I started here, but there is one thing, which is not solved - switching from image to image after the next one is loaded.

https://github.com/jirihelmich/ng-backstretch

**Comment by rprovost** [comment]
@jirihelmich Would you mind taking a look at this again? I've done a bit of work and cut a new release to address the lack of parity with the source jQuery backstretch library. Specifically, the issues you identified here.

**Comment by jirihelmich** [comment]
Hi, great! Kudos for the work. I will have a look, but I can't promise, when. Probably during the weekend.

**Comment by rprovost** [comment]
Excellent! Thank you. Whenever you get a chance. It's always nice to have more than a single set of eyes looking over things.

**Comment by rprovost** [comment]
@jirihelmich It seems there are a few others using this module now and this appears to be working for them. I'm going to close this issue for now.

**Comment by jirihelmich** [comment]
Yes. I'm really sorry, but I didn't have the chance to schedule a test of it. I will leave a note, when I'm able to do that.
